# Generated by Django 2.1.7 on 2020-03-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField(null=True)),
                ('videopic', models.ImageField(blank=True, null=True, upload_to='videopic')),
                ('videocontent', models.FileField(blank=True, null=True, upload_to='video')),
                ('uploadtime', models.DateTimeField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itube.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itube.Category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='itube.Tag')),
            ],
        ),
    ]
