# Generated by Django 2.1.7 on 2020-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0002_video_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
