# Generated by Django 2.1.7 on 2020-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaBlog', '0002_auto_20200120_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url_slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
