# Generated by Django 2.1.7 on 2020-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaBlog', '0003_articles_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url_slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
